### ISSUE TITLE
Training Data Apporach

### ISSUE THREAD

**Issue by kiranmaya** [zhangfaen/finetune-Qwen2-VL#11]
hi, I have images like this
![Screenshot_91](https://github.com/user-attachments/assets/4b6be093-8524-4c09-a575-b968fef535f6)
,after fine-tuning , if I give image later like this .
![Screenshot_85](https://github.com/user-attachments/assets/d675b98c-7360-4849-b2b9-812633558588)
I'm expecting it estimate score and reason how it is come its conclusion .how to prepare a dataset for this kind of problem .

**Comment by zhangfaen** [comment]
From human expert perpective,  expert reads an image and write down struct information text down. The struct information text can be describe by a json string (maybe). then you make many many such images and json string. then you make a train_data.json, then you finetune the model....

**Comment by kiranmaya** [comment]
i can make JSON in c# , I want to know structure for training data, I don't know the training data format .from what I understood , should I prepare , data like this 
`    {
        "messages": [
            {"role": "system", "content": "system prompt here"},
            {
                "role": "user",
                "content": [
                    {"type": "image", "image": "train_data/2.png"},
                  
                    {"type": "text", "text": "Prompt for estimation here"}
                ]
            },
            {
                "role": "assistant",
                "content": [
                    {"type": "text", "text": "estimated score is 456"}
                ]
            }
        ]
    },`

**Comment by zhangfaen** [comment]
Right. 

BTW, there is a example training data file in the repo: https://github.com/zhangfaen/finetune-Qwen2-VL/blob/main/train_data/data.json fyi
