### ISSUE TITLE
Qwen2-VL support detection

### ISSUE THREAD

**Issue by WangRongsheng** [zhangfaen/finetune-Qwen2-VL#12]
This will help you. In fact, qwen2-vl support object detection!

- https://github.com/QwenLM/Qwen2-VL/issues/9
- https://github.com/QwenLM/Qwen2-VL/issues/105
- https://github.com/QwenLM/Qwen2-VL/issues/190

**Comment by zhangfaen** [comment]
谢谢 Rongsheng提供的几个链接， 我快速看了一下里面的讨论， 发现 qwen-vl 和 qwen2-vl确实有考虑支持 object detection，但貌似qwen2-vl在object detection 性能上很差...  这个可能也是qwen2-vl发布的时候，没有刻意提 他们支持object detection的原因。 看起来 他们说 后续会提供一个方案。 

<img width="966" alt="image" src="https://github.com/user-attachments/assets/bbd940a5-2ba6-4f04-9d1e-0abf0bd14c72">

谢谢 上面的几个链接， 很有帮助。

**Comment by WangRongsheng** [comment]
Maybe this pr had solved this issue.

https://github.com/huggingface/transformers/pull/33487/files

**Comment by zhangfaen** [comment]
Thank you Rongsheng. https://github.com/huggingface/transformers/pull/33487/files looks a reasonable fix. Hope it will be merged into main branch of transformers lib.

In this repo, I may cherry pick that PR first and have another try.

**Comment by WangRongsheng** [comment]
look forward to it.
