### ISSUE TITLE
Some questions about the find_assistant_complet_stubist_indexes function

### ISSUE THREAD

**Issue by Asunatan** [zhangfaen/finetune-Qwen2-VL#24]
Hello, I am a beginner in the VLM field and I have some questions about the ground truth. In the find_assistant_comntent_stublist_indexes function, start_indexes=i+3 means that the three tokens<| im_start |>assistant \ n are ignored.
![image](https://github.com/user-attachments/assets/b62361bf-6c30-4ace-9b9c-5f89e4065b1a)

These three tokens do not calculate the loss, but in the official implementation of Qwen VL, it seems that the loss of these three tokens needs to be calculated. Here is the official implementation of Qwen VL：
![image](https://github.com/user-attachments/assets/6ef910c1-3b7d-4ebe-9730-bcc83f8f5d45)

**Comment by Asunatan** [comment]
Are you saying that there is not much difference between `start_indexes.append(i) ` and `start_indexes. append (i+3)`?

**Comment by zhangfaen** [comment]
<img width="743" alt="image" src="https://github.com/user-attachments/assets/50dd8dbf-1c06-43fa-828a-971fed9ef53c" />
I mean "to add or not to add" im_start token in the red box doesn't impact much.

**Comment by Asunatan** [comment]
So the loss calculation of the three tokens`<| im_start |>assistant \ n` doesn't matter, does it?

**Comment by zhangfaen** [comment]
I think so
